name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
      with:
        key: '20240901'
        cache-on-failure: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
